#I've opted not to use this workflow.
#This was supposed to work hand in hand with a Neon DB that I just created.
#However the DB stores timestamps in a different format with no option to change it to my timezone.
#This would leave all my previous data in a different timezone and the new data in the UTC format.
#I would also most likely need to modify the if conditions in index.php to use UTC as that's what github actions use.
name: Run PHP Script Twice Daily

on:
  schedule:
    - cron: "15 20 * * *"
    - cron: "15 13 * * *"
  workflow_dispatch:

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo, pdo_pgsql

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Set up .env
        run: |
          echo "DB_TYPE=${{ secrets.DB_TYPE}}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME}}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN}}" >> .env
          echo "DISCORD_CHANNEL=${{ secrets.DISCORD_CHANNEL}}" >> .env

      - name: Run script
        run: php index.php
